### ISSUE TITLE
Twitter Oauth Dance using SQLa Backend failing in current version (0.13), was working in version 0.11.1

### ISSUE THREAD

**Issue by avagut** [singingwolfboy/flask-dance#100]
The attached code file sets up a Twitter app with a SQLAlchemy backend.
On installing Flask Dance from pip install today currently (version 0.13), the code doesn't works.
If I manually download the package files code as it was in the commit 2ac2536473d4059c120e061de4d5ff7d8ac9e04a on 01 Aug 2017 and replace the pip installed files, the code works as expected and the auth dance is completed successfuly.

The code raises an error ValueError ("Cannot delete OAuth token without an associated user") and is not affecting GitHub and Google setups but affects Twitter.
[app txt](https://github.com/singingwolfboy/flask-dance/files/1565133/app.txt)

**Comment by singingwolfboy** [comment]
Hi @avagut, I didn't realize that the change in #92 would cause problems for existing setups. I've added some better documentation to explain what the problem is, and how you can modify your code to resolve it. Does that help?

I'd really appreciate if you could review that pull request, and if you find anything confusing, please add a comment to it and let me know! OAuth is complicated, and better documentation is one of the best way to make sure it gets implemented correctly.

**Comment by avagut** [comment]
Hi @singingwolfboy, thank you for the update. The expanded documentation shows the correct treatment well. Any apps built using the old pattern from the docs will have to pass in the parameter `user_required=False` to the blueprint backend, as a hack (call it, must-work-right-now-first-aid) before moving to the better reccomended approach. Great job!
