### ISSUE TITLE
Flask dance with twitch API

### ISSUE THREAD

**Issue by chanux** [singingwolfboy/flask-dance#123]
I have been trying to use flask-dance for Twitch API via OAuth2ConsumerBlueprint. The requests seem to fail since Twitch API expects client ID in request headers.

```DEBUG:requests_oauthlib.oauth2_session:Requesting url https://api.twitch.tv/user using method GET.
DEBUG:requests_oauthlib.oauth2_session:Supplying headers {u'Authorization': u'Bearer XXXXXX'} and data None
DEBUG:requests_oauthlib.oauth2_session:Passing through key word arguments {'allow_redirects': True}.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.twitch.tv
DEBUG:urllib3.connectionpool:https://api.twitch.tv:443 "GET /user HTTP/1.1" 302 154
DEBUG:urllib3.connectionpool:https://api.twitch.tv:443 "GET /kraken/base HTTP/1.1" 400 96
{u'status': 400, u'message': u'No client id specified', u'error': u'Bad Request'}
```

I have tried manually setting the headers and it seems to succeed  (even though it leaves new questions for me). I can not see how I can set custom headers. Is it possible?

**Comment by singingwolfboy** [comment]
Flask-Dance is built on top of [Requests](http://python-requests.org/). If you want to set custom headers, [you can do so the same way that you normally do with Requests](http://docs.python-requests.org/en/master/user/quickstart/#custom-headers). You can also set default headers on the [Session object](http://docs.python-requests.org/en/master/user/advanced/#session-objects).

Does that answer your question? If you get it working, it would be great if you could contribute a Twitch configuration for Flask-Dance, so others can use it. :smile:

**Comment by chanux** [comment]
I have tried to update the headers on session object. Still no luck. Maybe I'm doing something wrong :). I'd love to contribute a twitch blueprint if I managed get things to work.

Documenting the fruit of my misery so far to save precious time for the others who have to go through this 😆 


```python
app = Flask(__name__)
twitch_blueprint = OAuth2ConsumerBlueprint(
    "twitch", __name__,
    client_id='xxxx',
    client_secret='xxxx',
    base_url="https://api.twitch.tv/kraken",
    token_url="https://id.twitch.tv/oauth2/token",
    authorization_url="https://id.twitch.tv/oauth2/authorize",
    redirect_url="http://localhost:8080/authenticated",
    scope=('openid', 'user:read:email'),
)
# Trying to set headers twitch expects.
# Does not seem to work 
twitch_blueprint.session.headers.update({'Client-ID': twitch_blueprint.client_id})
app.register_blueprint(twitch_blueprint, url_prefix="/login")
twitch = twitch_blueprint.session
```

If you set `/login` as url_prefix above, you should set `http://localhost:8080/login/twitch/authorized` as `OAuth redirect URI` where you register your app with Twitch (It's **NOT** the same as redirect_url for flask-dance).

Also they have a new, incomplete(?) version of the API and everything is a bit more confusing because of this (even on their docs), at least for me.

**Comment by singingwolfboy** [comment]
The `session` property on an `OAuth2ConsumerBlueprint` instance is created lazily, and re-created for every incoming HTTP request that Flask handles. As a result, if you do `twitch = twitch_blueprint.session` _outside_ the scope of an incoming HTTP request, it will not work the way you expect.

Instead, your best bet is probably to write a factory function that defines the `session_created()` method to customize the Requests session before it is returned. You can update the session headers in that method, and I expect it will work correctly. Give that a try, and let me know how it goes!

https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/oauth2.py#L149-L174

**Comment by singingwolfboy** [comment]
@chanux Did you have any luck implementing this with the `session_created()` method?

**Comment by ajrab** [comment]
Hey @singingwolfboy, I was having the same issue. Unfortunately, I attempted to change the `session_created()` method as suggested but encountered a new issue. The header that Twitch needs is `Authorization: Bearer <access token>` but I'm under the impression that we need to already have created the session in order to receive the access token... or at least that's what the recursion error I'm getting is leading me to believe.

Any help would be much appreciated!

Here's my edited method if it helps:

<pre>def session_created(self, session):
  self.session.headers.update({'Authorization': "Bearer {}".format(self.session.token)})
  return session</pre>

**Comment by singingwolfboy** [comment]
The `session_created()` blueprint accepts `session` as an argument. Try taking out the `self` reference and just using that argument, instead. Like this:

```python
def session_created(self, session):
  session.headers.update({'Authorization': "Bearer {}".format(session.token)})
  return session
```

Does that work?

**Comment by singingwolfboy** [comment]
Also, the `Authorization` header is part of the OAuth standard, so Flask-Dance should set that automatically. You don't need to add it manually in the `session_created` method. @chanux says that you need to pass a custom `Client-ID` header, which is _not_ part of the OAuth standard, and that's why I suggested using the `session_created` method. Is the `Authorization` header not being set correctly for you?

**Comment by ajrab** [comment]
Cheers, that helped me figure out the issue -- I've got everything working perfectly now! It seems that the issue was that the `base_url` needs to be `"https://api.twitch.tv/helix/"` and not `"https://api.twitch.tv/kraken"`. The Twitch-provided documentation on this is quite difficult to swim through as @chanux said.

Here's what the blueprint should look like (with the actual scopes in place of scope1/2/3 and your actual URI...):

```
twitch_blueprint = OAuth2ConsumerBlueprint(
    "twitch", __name__,
    client_id='xxxx',
    client_secret='xxxx',
    base_url="https://api.twitch.tv/helix/",
    token_url="https://id.twitch.tv/oauth2/token",
    authorization_url="https://id.twitch.tv/oauth2/authorize",
    redirect_uri='http://127.0.0.1:5000/',
    scope=('scope1', 'scope2', 'scope3')
)

app.register_blueprint(twitch_blueprint, url_prefix="/login")
```

And if you want the current user's information:

```
twitch_user_info = twitch_blueprint.session.get("users").json()
print("You are {username} on Twitch".format(username=twitch_user_info['data'][0]['display_name']))
```

Other available user info is documented here: https://dev.twitch.tv/docs/api/reference/#get-users.

Thanks for putting up with my nonsense question @singingwolfboy 😉(and for the library!)

**Comment by singingwolfboy** [comment]
Great! Would you like to send a pull request for a Twitch configuration?

**Comment by ajrab** [comment]
Sure thing, I'll put one in as soon as I finish the app I'm building with Flask-Dance

**Comment by tcmRyan** [comment]
@singingwolfboy  I'm running into this issue on writing a Zoho configuration, they want 'Zoho-oauthtoken' instead of 'Bearer'.  I'm having trouble figuring out where to modify the session. I edited 
https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/oauth2.py#L173 to be:
```
    def session_created(self, session):
        try:
            session.headers.update({'Authorization': 'Zoho-oauthtoken {}'.format(session.token)})
        except ValueError:
            # Needed to avoid error on startup
            log.info("Unable to fetch token")
        return session
```
But when I dropped it into the debug it looks like it doesn't get called before making my get request to ZohoCRM.

This works in the logged in view:
`resp = requests.get('https://www.zohoapis.com/crm/v2/users', params={'type': 'CurrentUser'}, headers={'Authorization': 'Zoho-oauthtoken {}'.format(token['access_token'])})` 
This results in a connection pool error with the Authorization header still being 'Bearer':
`resp = bp.session.get("/users", params={'type': 'CurrentUser'})`

**Comment by singingwolfboy** [comment]
Hey Ryan, could you please open a new issue instead of reopening this one? You can definitely link to this issue if it has some useful context, but I try to have one problem per issue, not more.

**Comment by fenhl** [comment]
Hey @ajrab, any updates on that Twitch PR?

**Comment by fenhl** [comment]
I implemented this at [wurstmineberg.de](https://github.com/wurstmineberg/wurstmineberg.de) and am getting the error “oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.” Any idea what could be wrong?

**Comment by vincentjr** [comment]
I'm seeing that as well @fenhl , did you ever figure it out?

**Comment by fenhl** [comment]
No, the error still exists.

**Comment by vincentjr** [comment]
Think I just got it @fenhl:

```
twitch_bp = OAuth2ConsumerBlueprint(
        "twitch",
        __name__,
        client_id=client_id,
        client_secret=client_secret,
        scope=scope,
        base_url="https://api.twitch.tv/helix/",
        authorization_url="https://id.twitch.tv/oauth2/authorize",
        token_url="https://id.twitch.tv/oauth2/token",
        redirect_url=redirect_url,
        redirect_to=redirect_to,
        login_url=login_url,
        authorized_url=authorized_url,
        session_class=session_class,
        storage=storage,
        token_url_params={"include_client_id": True}
    )
```

Add that token_url_params. I also changed the base_url, don't think that matters.

**Comment by kerryhatcher** [comment]
@ajrab @fenhl  and @vincentjr would y'all mind taking a look at https://github.com/singingwolfboy/flask-dance/pull/348 and seeing how it compares to your blueprints?

**Comment by fenhl** [comment]
Just upgraded to Flask-Dance 4 and the new Twitch blueprint seems to work correctly. Thanks all!
