### ISSUE TITLE
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 2 - probably unsupported type

### ISSUE THREAD

**Issue by Hammit** [singingwolfboy/flask-dance#126]
I have a problem using Flask-Dance. I have adapted the [Multi-User GitHub Setup](https://flask-dance.readthedocs.io/en/latest/multi-user.html) to use Google. I get this error after doing the OAuth login with Google...

sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 2 - probably unsupported type. [SQL: 'INSERT INTO flask_dance_oauth (provider, created_at, token, provider_user_id, user_id) VALUES (?, ?, ?, ?, ?)'] [parameters: ('google', None, {'access_token': '<A_LONG_ACCESS_TOKEN>' ... (833 characters truncated) ... -jN4yWZu6r1H8wZmspwZRxhbbyia20NX9XfQ4IWDRA7wgAX8-61C_dsBUI8DH49cTFfKCHSyUCb93ItUqiis8DEocQ', 'token_type': 'Bearer', 'expires_at': 1526023334.0467675}, '<THE_USER_ID>', 1)] (Background on this error at: http://sqlalche.me/e/rvf5)

It looks like Flask-Dance or a dependency is trying to save the token to the Db and is producing the InterfaceError seen. I believe the token is a dict or some object, but the DB column type is TEXT in my case as I'm just using SQLite atm. Is this the problem? As a hack/workaround/test, I tried to stringify the token manually when creating the OAuth object as in the guide provided, and that bypasses this problem, but I run into other issues as a result of the token not inflating properly from the Db I believe.

**Comment by Hammit** [comment]
Here is a minimal [Gist](https://gist.github.com/Hammit/f4717c54eb7f70b41573ebb0d5ce96b8) to reproduce the issue.

**Comment by singingwolfboy** [comment]
It's simplest to make your database model inherit from the `OAuthConsumerMixin` class, [as documented here](http://flask-dance.readthedocs.io/en/latest/backends.html#sqlalchemy). That class defines the columns that Flask-Dance expects on the database model. Try inheriting from that class, and see if it resolves your problem.

If that _does_ solve it, is there a way that we can improve the documentation or the code to make it easier to figure out how to solve this problem in the future?

**Comment by Hammit** [comment]
The reason I haven't used the `OAuthConsumerMixin` class is because I sometimes work with systems where the schema is already defined. In this case I reflect the Db tables and go from there.

To get the SQL code for the flask_dance_oauth table, I created a basic app that did use the mixin and had a look at the SQL it generated and used that as my base. However, I've just noticed then by looking at the `OAuthConsumerMixin` source that the token field is 'special'.

`token = Column(MutableDict.as_mutable(JSONType))`

So, I guess you're probably right in saying to use the mixin. I would however like to be consistent in my approach to doing Db models, and not mix and match. Do you see a way around this for people who use reflection?

**Comment by Hammit** [comment]
Also wanted to note that reflecting Db tables and using `OAuthConsumerMixin` doesn't work well when combined as it gives the following error...

sqlalchemy.exc.InvalidRequestError: Table 'flask_dance_oauth' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.

**Comment by singingwolfboy** [comment]
Ah, I hadn't considered the use-case where you want to reflect tables that already exist in your database. Thanks for bringing this up!

In the SQLAlchemy documentation, it appears that [it's possible to override reflected columns](http://docs.sqlalchemy.org/en/latest/core/reflection.html#overriding-reflected-columns), which is probably what you want to do here. The basic idea is that Flask-Dance is using the [JSONType](https://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html#module-sqlalchemy_utils.types.json) column type provided by SQLAlchemy-Utils in order to treat the `token` column as a JSON-encoded dictionary. SQLAlchemy's database reflection sees a text column, and assumes you want to use a [Text](http://docs.sqlalchemy.org/en/latest/core/type_basics.html#sqlalchemy.types.Text) column type, but this assumption is wrong.

I don't know much about how to handle this situation correctly, since I've never tried to do so. Can you give it a try, and let me know what works? If you get it working correctly, I would really appreciate if you could make a pull request to update the documentation, so others can learn from your experience! (The documentation is in the `docs` directory of this repository.)

**Comment by singingwolfboy** [comment]
By the way, in the Gist you showed me, there's no reason to pass the client ID and client secret to the blueprint factory function, as you're doing on lines 71 and 72. If you use the names `GOOGLE_OAUTH_CLIENT_ID` and `GOOGLE_OAUTH_CLIENT_SECRET` in the `app.config`, Flask-Dance will pick them up automatically. [This is documented in the Providers documentation.](http://flask-dance.readthedocs.io/en/latest/providers.html#module-flask_dance.contrib.google)

**Comment by Hammit** [comment]
I doubt that would be a clean or possible solution in my case. The reflection is done by Flask-SQLAlchemy.

I was trying to set `extend_existing=True` in the call to [SQLAlchemy MetaData reflect](http://docs.sqlalchemy.org/en/latest/core/metadata.html#sqlalchemy.schema.MetaData.reflect), however, I'm using Flask-SQLAlchemy, which has it's own reflect method that doesn't use or allow this setting.

I modified Flask-SQLAlchemy to allow extra kwargs to be passed through to the SQLAlchemy call to reflect, but this didn't work as I still got the same error :(
