### ISSUE TITLE
OAuth flow using Facebook

### ISSUE THREAD

**Issue by erwinyusrizal** [singingwolfboy/flask-dance#128]
Hi, I'm having problem to login using Facebook, it stucks here `https://ccef119x8.ngrok.io/login/facebook/authorized?code=AQDpFCaE1V1OkhzeBROdhjI0QhmggIrtVuI7diOxs9`

```
facebook_auth = make_facebook_blueprint(
    client_id='<client_id>',
    client_secret='<secret_id>',
    scope=['email'],
    authorized_url='https://ccef119x8.ngrok.io/login/facebook/authorized'
)
```

I use `oauth_authorized` decorator but the process it's not there yet, it stucks as I said above

Any idea? 
Thank you

**Comment by singingwolfboy** [comment]
I'm sorry, I don't understand what the problem is. Can you provide a more detailed bug report? In particular, please include:

* The behavior that you _expect_ to occur
* The behavior that _actually_ occurs
* A complete Flask application that another developer can use to reproduce the problem (this doesn't need to include OAuth IDs and secrets, as long as the developer can create their own OAuth ID and secret)

**Comment by erwinyusrizal** [comment]
@singingwolfboy sorry it was my mistake, all good now, thanks
