### ISSUE TITLE
Add OAuth provider support

### ISSUE THREAD

**Issue by drryanjames** [singingwolfboy/flask-dance#140]
Hey @singingwolfboy,

Awesome library. My team and I would like to use it but need provider support. We're currently using the outdated [Authomatic](https://github.com/authomatic/authomatic) to authenticate users through the consumer OAuth flow, and [Flask-OAuthlib](https://github.com/lepture/flask-oauthlib) to auth our apps  through the provider OAuth flow. We're considering replacing both of these libraries with [Authlib](https://github.com/lepture/authlib) because it supports both consumer and provider flows and seems to be well maintained. We would rather use flask-dance because it's also well maintained and is built on top of [oauthlib](https://github.com/oauthlib/oauthlib), but your docs say flask-dance doesn't currently support the provider flow, only the consumer flow, and we need both.

Except from the docs:
```Currently, only OAuth consumers are supported, but this project could easily support OAuth providers in the future, as well.```

Do you have plans to support the provider flow any time soon?

If you can describe the work that needs to be done we will consider contributing. We're still working on our final budget for our auth work and, if we can swing it, we'd like to help.

Thanks for creating flask-dance!

**Comment by singingwolfboy** [comment]
Thank you! I'm glad you like Flask-Dance. :smile:

I built this project based on the [YAGNI](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it) approach, and so far, I haven't needed to build an OAuth provider. I left space in the project for that feature to exist: you'll notice that almost all the code is scoped under `flask_dance.consumer`, specifically so that `flask_dance.provider` could exist in the future. However, I haven't started working on this myself, and I don't have any plans to do so in the near future (because I still don't need to build an OAuth provider for myself).

If you would like to work on building this feature, I would love to work with you and add it to Flask-Dance! However, you would be doing most of the work yourself, which is probably not a very appealing option. If Authlib fits your needs and helps your team move faster, then that's probably a better option for you. If Authlib _doesn't_ fit your needs, then this is an opportunity to custom-build _exactly_ what you need, and I can help you make that code generic enough to put into Flask-Dance.

What do you think?

**Comment by drryanjames** [comment]
Awesome! I'll let you know asap.

**Comment by singingwolfboy** [comment]
Off the top of my head, I believe we'll need database models for the following:

* OAuth apps (one user can create multiple apps), where each app has a `client_id` and `client_secret`
* OAuth scopes, ideally written in such a way that it integrates with [Flask-Principal](https://github.com/mattupstate/flask-principal) or [Flask-Permissions](https://github.com/raddevon/flask-permissions), so that routes can indicate which OAuth scopes are required
* OAuth grants, to track which users have granted consent to which apps. Each grant has a unique authorization token, which is returned to the OAuth consumer after the user grants consent.

We'll also need to implement a page for the user to grant consent for the request. It will need to display information about the OAuth app and the scopes that the OAuth consumer is requesting. It's going to be a challenge to make sure that this page is flexible enough that a developer can customize how it's displayed -- I suggest looking at the [Flask-Admin](https://flask-admin.readthedocs.io/) project for an example of how to do that.

The [OAuth spec](https://tools.ietf.org/html/rfc6749) is long and complicated, and it defines six different grant types that all work differently. (It's so complicated that someone make [a pretty-looking website just to make it all easier to understand](https://oauth.net/2/)!) I strongly recommend following the YAGNI approach, and only implementing the things that _you_ need to make this work, while not closing off the code to further changes in the future.

For example, if you only need one of the six grant types, only implement that one. However, the code should still allow a developer to indicate which grant type she/he is interested in. If the developer indicates the grant type that you've implemented, then great! It all works. If the developer indicates any other grant type, then the code fails with a [`NotImplementedError`](https://docs.python.org/3/library/exceptions.html#NotImplementedError).

Does that give you a good idea of the effort involved? Do you have other questions I can answer?

**Comment by drryanjames** [comment]
I tried to work it in, but we don't have the budget to do this work right now. We'll have a more pressing need for the provider flow if/when our existing library (Flask-OauthLib) loses support and stops working.

Thanks for the details and this library. I just integrated it in place of Authomatic and things are working well.

**Comment by drryanjames** [comment]
Thanks again. Flask-Dance is working great in place of Authomatic. Closing this.

**Comment by xmedeko** [comment]
I would like to have a provider support as well based on the . Unfortunately, I have no experience with Flask or other pythn web development, so I'll try the [Authlib](https://github.com/lepture/authlib).

IMO you should leave this issue opened to catch some user votes.
