### ISSUE TITLE
Wrong session usage or possible security issue

### ISSUE THREAD

**Issue by yuvadm** [singingwolfboy/flask-dance#163]
Working according to the basic documentation, I'm hitting a serious problem where one user login session in one browser is propogated to another browser with no login credentials.

Here's my relevant server code:

```python
from os import environ

from flask import Flask, redirect, url_for, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_dance.contrib.twitter import make_twitter_blueprint, twitter
from flask_dance.consumer.backend.sqla import SQLAlchemyBackend, OAuthConsumerMixin
from werkzeug.contrib.fixers import ProxyFix


app = Flask(__name__)
app.secret_key = environ.get('FLASK_SECRET_KEY')
app.wsgi_app = ProxyFix(app.wsgi_app)
app.config.from_object('config.Config')

db = SQLAlchemy(app)
migrate = Migrate(app, db)

class OAuth(OAuthConsumerMixin, db.Model):
    pass

twitter_blueprint = make_twitter_blueprint(
    api_key=app.config['TWITTER_CONSUMER_KEY'],
    api_secret=app.config['TWITTER_CONSUMER_SECRET'],
)
twitter_blueprint.backend = SQLAlchemyBackend(OAuth, db.session)
app.register_blueprint(twitter_blueprint, url_prefix='/login')


@app.route('/')
def index():
    username = None
    if twitter.authorized:
        resp = twitter.get('account/settings.json')
        username = resp.json()['screen_name']
    return render_template('index.html', username=username)
```

Steps:

1. Open two separate browser sessions
2. In both sessions, navigate to `server:5000`, homepage shows a login link `{{ url_for('twitter.login') }}`
3. On browser `A`, perform Twitter authentication dance
4. Redirect back to homepage, `username` is rendered correctly, inspecting the SQL database, the oauth tokens are indeed saved correctly for the user
5. On browser `B` refresh homepage, `username` is now populated with the login session from browser `A`

Other notes:

- Happens on all environments, both with and without flask debug mode, as well as running through gunicorn
- Backend database is a postgreSQL instance
- Flask 1.0.2, Flask-dance 1.0.0, Python 3.7
- Adding `user_required=False` as a param to `SQLAlchemyBackend` doesn't change this behavior

This is no doubt a serious potential security bug. Either the library is behaving in an unexpected way, or I'm doing something wrong, and hitting a pitfall, in which case the documentation probably should be updated to warn about this behavior.

**Comment by yuvadm** [comment]
Further digging into the issues it seems this might be related to the behavior mentioned in #88 but as far as I can tell there's still some buggy behavior going on.

**Comment by yuvadm** [comment]
@singingwolfboy Awesome, thanks! If there's anything I can do to help speed up the debugging, please let me know.

**Comment by singingwolfboy** [comment]
Wait a second. After looking at the code more, I don't see any code for managing users in the code sample you posted above. As a result, everyone visiting your website will use the same Twitter account.

If you want a multi-user system, where each user of your application is connected to a different Twitter account, [check the documentation for multi-user setups with Flask-Dance](https://flask-dance.readthedocs.io/en/latest/multi-user.html).

After reviewing the documentation, you're correct that this distinction is not as clear as it should be. After we resolve your issue, can you help out with writing the documentation that you _wish_ you had seen initially? As the person who wrote this library, the distinction seems obvious to me, which is why I need assistance from people like you who can approach this library with a fresh perspective.

**Comment by yuvadm** [comment]
Sure I'd love to help document this better. I guess the most obivous pitfall here for me is the concept of a *non-multi-user setup*. In what context is this behavior that I'm witnessing useful?

**Comment by singingwolfboy** [comment]
Mostly for writing bots that respond to webhook events. That's actually the context in which this project was born. I was working for [edX](https://www.edx.org/), and we needed a system to keep our [JIRA](https://openedx.atlassian.net/) and GitHub in sync. I created the [openedx-webhooks](https://github.com/edx/openedx-webhooks) project, which responds to webhook events from GitHub and propogates the changes on JIRA, and vice versa.

Does that make sense?

**Comment by yuvadm** [comment]
Interesting, yeah I guess that's reasonable. I'll see if I can propose a documentation fix that makes this issue clear. Thanks for the quick response!

**Comment by daenney** [comment]
If you're working with actual users I'd recommend taking a look at Flask-Login and see if that fits your needs, or go for the superset of Flask-Security if you also need a permission system and some other niceties.

**Comment by yuvadm** [comment]
@daenney My actual use case doesn't really require handling actual users, just collecting oAuth tokens, something that resembles what @singingwolfboy originally had in mind. So I'm essentially doing something like this:

```python
@oauth_authorized.connect_via(twitter_bp)
def twitter_logged_in(blueprint, token):
    if token:
        oa = OAuth(provider=blueprint.name,token=token)
        db.session.add(oa)
        db.session.commit()
    return False
```

I'm not using any of what flask-security provides (since I don't really need it) and as a workaround for the default behavior of the "global" session I'm just not writing user data to the response.

**Comment by singingwolfboy** [comment]
@yuvadm That seems like it should work. Are you still planning to send a documentation pull-request?

**Comment by yuvadm** [comment]
@singingwolfboy Yeah but right now I don't have anything more to suggest than just a warning about this pitfall.

The session behavior still is very counter-intuitive IMO, and maybe needs a better fix regardless.

**Comment by singingwolfboy** [comment]
@awiddersheim @yuvadm: I just did some research in the Flask documentation, and it appears that your assumption is incorrect. Both the `g` object and the `google` are indeed context local objects, but the word "context" refers to [application context](http://flask.pocoo.org/docs/1.0/appcontext/), not [request context](http://flask.pocoo.org/docs/1.0/reqcontext/). As a result, multiple requests within the same application _do_ share the same `g` object and `google` object, and that is _intentional_.

This is definitely a bit confusing -- as I said, I had to do some research to confirm that my suspicions were correct on this. Is there a way we can improve the documentation to make this clearer?

**Comment by awiddersheim** [comment]
@singingwolfboy Hrm, reading the same docs you are from Flask and I get the opposite impression. Especially the parts in [Storing Data](http://flask.pocoo.org/docs/1.0/appcontext/#storing-data).

> The g name stands for “global”, but that is referring to the data being global within a context. The data on g is lost after the context ends, and it is **not an appropriate place to store data between requests**. Use the session or a database to store data across requests.

**Comment by awiddersheim** [comment]
I think my problem relates to me running with gunicorn and threaded workers which seems like a no go  when using flask-dance since some state gets shared on the blueprint and not in the app or requests contexts. If I were to run without threads, it'd probably be fine. 

A good example highlighting the problem, but is certainly not the only thing, is the [following](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/oauth2.py#L232):

```
self.session._state = state
```

Since the blueprint gets shared between all threads/requests, the above code will result in problems when using the proxy that gets created by each provider. Actually, using threads is a security risk as suggested by the original poster and as I mentioned in my original post.

I think the ideal solution for this problem, other than just not using threads, would be to continue creating a proxy that is in the app context similar to the [following](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/contrib/google.py#L127):

```
    @google_bp.before_app_request
    def set_applocal_session():
        ctx = stack.top
        ctx.google_oauth = google_bp.session

    return google_bp

google = LocalProxy(partial(_lookup_app_object, "google_oauth"))
```

Perhaps a more generic name similar to Flask-Login's `current_user` (e.g. `current_oauth_session`) and make sure every reference, even in the blueprint, refers to that instantiation. Basically, using `current_oauth_session` just like you use `flask.session` or `flask.request`, etc.

Also, I really hate all the `@lazy` decorators going on but to each their own.

Honestly, the fact that there are proxies now made available by each provider gave me the impression this was thread/request safe since that is typically the case with the other flask proxies like `flask.g`, `flask.session`, etc.

**Comment by singingwolfboy** [comment]
I believe that Flask-Dance *is* threadsafe, but I haven't actually tested. If you can come up with a minimal testcase that show that Flask-Dance, by itself, is _not_ threadsafe, then I'd be very interested to see and and figure out where the problem is.

You referenced [the following line of code](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/oauth2.py#L232):

```python
self.session._state = state
```

That `state` object is stored in the `flask.session`, and is only attached to the `self.session` object because that object is a Requests-OAuthLib [OAuth 2.0 Session](https://requests-oauthlib.readthedocs.io/en/latest/api.html#oauth-2-0-session) object, and it uses the `_state` property when calling [`fetch_token()`](https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/oauth2_session.py#L186-L187). That `_state` property shouldn't need to live beyond a single request, and I wouldn't expect it to do so.

**Comment by awiddersheim** [comment]
The `state` in my example isn't the problem, the `session` is.

**Comment by singingwolfboy** [comment]
I’m confused. What’s wrong with having an OAuth session object? That’s what Flask-Dance used to do all OAuth-related work.

**Comment by awiddersheim** [comment]
The issue is when you go to use the session. In my case, whne I use the `google` proxy to validate users. That session lives on the blueprint, which is shared between _all_ threads and requests. That single session instance gets updated with things like the `state` from many different requests at any given time.

**Comment by singingwolfboy** [comment]
After talking with @awiddersheim about this a few days ago, it appears that Flask-Dance is _not_  threadsafe, and so should only be used in a multi-process worker model, _not_ with multi-threaded workers. However, he wasn't able to come up with an automated test to demonstrate the problem, so I haven't been able to reproduce it or fix it.

I'm going to close this GitHub issue, since it appears that we've strayed very far from @yuvadm's original question. If @awiddersheim (or anyone else) wants to open a separate GitHub issue focused on multi-threaded support for Flask-Dance, that would be fine with me, but this is not a priority for me right now.
