### ISSUE TITLE
Multithreading support

### ISSUE THREAD

**Issue by danlamanna** [singingwolfboy/flask-dance#205]
From #163/@singingwolfboy:
> I'm going to close this GitHub issue, since it appears that we've strayed very far from @yuvadm's original question. If @awiddersheim (or anyone else) wants to open a separate GitHub issue focused on multi-threaded support for Flask-Dance, that would be fine with me, but this is not a priority for me right now.

We recently switched to a multi-threaded worker model approach and noticed issues from `flask_dance` (technically from the lazy library):
```
KeyError: 'session'
  File "raven/middleware.py", line 20, in common_exception_handling
    yield
  File "raven/middleware.py", line 100, in __call__
    iterable = self.application(environ, start_response)
  File "werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "flask/app.py", line 2303, in wsgi_app
    ctx.auto_pop(error)
  File "flask/ctx.py", line 434, in auto_pop
    self.pop(exc)
  File "flask/ctx.py", line 400, in pop
    self.app.do_teardown_request(exc)
  File "flask/app.py", line 2145, in do_teardown_request
    func(exc)
  File "flask_dance/consumer/oauth2.py", line 177, in teardown_session
    lazy.invalidate(self, "session")
  File "lazy/lazy.py", line 51, in invalidate
    del inst.__dict__[name]
```

`name` doesn't exist in `inst.__dict__` on the very next line after checking for it.

**Comment by daenney** [comment]
If the problem is caused by the lazy library it seems that's where this bug report should be filed against? Afaik there's nothing in Flask-Dance itself that would be sensitive to multi-threading, in so far as Flask is able to handle it.

**Comment by duaneking** [comment]
I have to agree with @daenney here, this doesn't look like the correct place to report the bug; Filing it in werkzeug would even be a better choice than here but since the exception is being thrown in raven why not post this there?

**Comment by daenney** [comment]
There's a number of things we need to consider with regards to thread safety:

* Flask itself remains thread-safe (according to its authors) by levering context locals and the app and request contexts. We'd need to ensure we don't do anything outside of them (aside from loading settings). It's also not really clear how to test for this.
* We'll need to check our own code for thread safety. There's a lot of gotchas in Python w.r.t that, such as `counter +=1` being thread safe b/c it's implemented as a single operation but `counter = counter + 1` not, b/c it's multiple operations. Which operations are and aren't is also a concern as this is largely an implementation detail of CPython and might not hold true on PyPy for example. It might also be dependent on the runtime version.
* Our dependencies aren't necessarily thread safe, b/c a lot of things in the Python ecosystem aren't written with thread safety in mind. There's a question on what would happen/how it would interact if we were to use a non-threadsafe dependency even if Flask-Dance itself remains thread safe. Since we're handling sensitive data we need to be able to guarantee we don't leak anything across threads.

If anyone can provide definitive/authoritative answers to that last one and define a proper strategy on testing all of this we might be able to figure out a way forward.

However, as it currently stands, our recommendation is to run your app in a multiprocess/prefork model, which is what mod_wsgi and uWSGI do by default.

**Comment by daenney** [comment]
In the mean time the lazy library has been removed in 2.0 so you might have better luck. All of https://github.com/singingwolfboy/flask-dance/issues/205#issuecomment-473218336 still applies though.
