### ISSUE TITLE
Google Multi-User Setup: "provider_user_id" same as "user_id"?

### ISSUE THREAD

**Issue by KurtKline** [singingwolfboy/flask-dance#242]
First of all, just wanted to say thank you for creating Flask-Dance. Seems to be an extremely powerful package.

I would like to clarify the intended column specification for the OAuth table for a Google multi-user setup. On the "Multi-User Setups" page of the docs, an OAuth object is initialized in the following way: 

```
oauth = OAuth(
            provider=blueprint.name,
            provider_user_id=github_user_id,
            token=token,
        )
```

However, on the "Token Storages" page, the OAuth table is setup as follows: 

```
class OAuth(OAuthConsumerMixin, db.Model):
    user_id = db.Column(db.Integer, db.ForeignKey(User.id))
    user = db.relationship(User)
```

Are the "provider_user_id" and "user_id" referring to the same field? Or should the OAuth class have both a "user_id" (which links to the User table's "id" column) and a "provider_user_id"?

**Comment by singingwolfboy** [comment]
No, they are not the same. The `user_id` field is a foreign key to the `User` model in your application, and it is required if you want to use multi-user setup with SQLAlchemy. The `provider_user_id` field is not required -- it's a way of recording the user ID of the user on the *OAuth provider's* website. This is mostly useful for being able to look up the local user that matches the ID from the OAuth provider.

It's a common misconception that, because a user can log in to your website using OAuth instead of creating a new username/password combination, that means they do not have a user account on your website. This is false. Logging in with OAuth *does create a local user account*, and that user account will have a `user_id`. The `user_id` on that account does *not* have to match that user's ID on Google, or Facebook, or Twitter, or whatever OAuth provider(s) you choose to use. That's why they need to be two separate properties on the `OAuth` model, which map to two separate columns in the database table.

[The documentation on logging out](https://flask-dance.readthedocs.io/en/latest/logout.html#local-accounts-vs-provider-accounts) provides some more information about this, and you can also look at [an example quickstart project](https://github.com/singingwolfboy/flask-dance-twitter-sqla/blob/master/app/oauth.py#L31-L47) to see how this field is used in the login process.

Does this clarify the situation? If so, can you please provide some feedback on how we could improve the documentation to make this less confusing for other people? (Or even better, [send a pull request to improve the docs](https://github.com/singingwolfboy/flask-dance/tree/master/docs)?)

**Comment by KurtKline** [comment]
Thank you for the lightning fast response. 

The documentation on logging out cleared things up for me conceptually (having both a provider_user_id and a user_id that is a foreign key to the User model). 

In order to be 100% confident in the implementation, here is what I ended up with: 

```
class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    email = db.Column(db.Text)

class OAuth(OAuthConsumerMixin, db.Model):
    user_id = db.Column(db.Integer, db.ForeignKey(User.id))
    user = db.relationship(User)
    provider_user_id = db.Column(db.Numeric)
```

With the inherited columns from OAuthConsumerMixin, the resulting columns for OAuth are: id, provider, created_at, token, user_id, provider_user_id

I was also required to add UserMixin to the User model, because without it I received this error: "AttributeError: 'User' object has no attribute 'is_authenticated'"

**Comment by KurtKline** [comment]
@singingwolfboy do you have some thoughts on this? 

Also, I would be more than happy to send a pull request to improve the docs once I get it all implemented.

**Comment by singingwolfboy** [comment]
Seems reasonable to me! The only thing I would change is that there’s no reason we need to assume that provider_user_id has to be numeric. Providers can use whatever format or scheme they want for assigning IDs, and some of them may include non-numeric characters. I recommend using a db.String or db.Text instead.

**Comment by KurtKline** [comment]
Thank you for the heads up on the numeric type!

**Comment by singingwolfboy** [comment]
I'm closing this issue due to a lack of updates.
