### ISSUE TITLE
should the provider_user_id & access token be hashed & salted?

### ISSUE THREAD

**Issue by mark-schulze** [singingwolfboy/flask-dance#251]
Like the title says, I‘m unsure whether this could be compromised and misused otherwise.

thnks

**Comment by daenney** [comment]
Depends a bit; `user_id` not really, much like you wouldn't hash and salt regular usernames in your database.

The tokens you get come in three types roughly
* short-lived tokens
* refresh tokens
* offline tokens

Short-lived tokens have a short life expectancy, this tends to be anywhere between a minute to an hour from what I've seen. Even if those are compromised, they're not useful for very long.

Refresh tokens and offline tokens are important. Refresh tokens allow you to get a new short-lived token, and offline tokens don't expire by themselves.

For those tokens, you should hash them, but there's not necessarily a need to salt them. Tokens are randomly generated using a secure random generator. At that point rainbow tables aren't a feasible way to attempt to recover the plaintext anymore. We normally hash in order to protect people with weak passwords, tokens don't fall in that same category. All of this is of course dependent on your Oauth provider not being completely moronic and not generating weak/predictable tokens.

In the event of a compromise, the user has a relatively easy course of action, revoke the token at the oauth provider, rendering it innocuous. Should you ever get compromised, regardless of whether you've hashed those tokens or not, ensure you have a way to notify your users so they can take action.

**Comment by mark-schulze** [comment]
Ok thank you, that clears up a lot.

This is what I get back from my provider:

`{"access_token": "short_token.len30", "expires_in": 3600, "token_type": "Bearer", "scope": ["email~s", "aq:name", "openid", "userinfo", "aq:push"], "refresh_token": "short_token.len30", "state": null, "id_token": "very_long_token= string.len459 ", "expires_at": 1556397515.9152918}`

**Comment by daenney** [comment]
The ID token isn't that interesting:

> The ID Token is a JSON Web Token (JWT) that contains user profile information (such as the user's name and email) which is represented in the form of claims. These claims are statements about the user, which can be trusted if the consumer of the token can verify its signature.
>
> You can get an ID Token for a user after they successfully authenticate.

**Comment by mark-schulze** [comment]
ok, well then I feel pretty safe actually. Thanks again!
