### ISSUE TITLE
Redirecting after OAuth dance AND using multi-user setup

### ISSUE THREAD

**Issue by jmprovencher** [singingwolfboy/flask-dance#270]
Based on the documentation, when using [multi-user setup ](https://flask-dance.readthedocs.io/en/latest/multi-user.html) we're supposed to return False to disable Flask default behavior for saving the token. With the new update regarding #253 ,  now if we want to redirect, we need to do this after the `@oauth_authorized` signal.
```python
@oauth_authorized.connect
def logged_in(blueprint, token):
    blueprint.token = token
    next_url = flask.session["next_url"]
    return flask.redirect(next_url)
```

How can we return a flask.redirect and return False at the same time in the same method? 
It does not seem possible to me. Is there a new behaviour I need to know in order to disable the default token saving?

**Comment by singingwolfboy** [comment]
As @cancan101 [pointed out in a comment on #203](https://github.com/singingwolfboy/flask-dance/issues/203#issuecomment-486322894), returning a `Response` object (such as the one created by `flask.redirect()` and returning `False` _both_ prevent the token from being saved to the storage.

Clearly, we need to improve the documentation for this. Where is the best place to put this information? @jmprovencher, you might be the best person to resolve this confusion, since you're experiencing it right now. Do you think you could send a pull request to the `docs` folder in the codebase, to help improve the documentation?

For reference, [here is the relevant code that gets called if you return a `Response` object](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/oauth2.py#L274-L275). Notice now [the code to set the token to the storage](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/oauth2.py#L281) is below it, so it will never get called if the function returns early.

**Comment by jmprovencher** [comment]
Yes I'll make a pull request today ! Let me know I'm not clear in it!
