### ISSUE TITLE
Using oauth for programmatic access

### ISSUE THREAD

**Issue by jimcarreer** [singingwolfboy/flask-dance#275]
I've got flask dance working for Okta.  The redirect / login flow is fine via a browser, but what if I want to provide programmatic access to my applications API? Does flask-dance support that, if so is there some documentation I can look at related to doing this?

**Comment by daenney** [comment]
I'm not 100% sure, but I imagine this would work:
* After the login flow, you return the token to the user
* They then call your API with `Authorization: Bearer <token>`
* You grab the token from the auth header, call the Oauth provider's token validation endpoint and if it passes then act on their request

**Comment by jimcarreer** [comment]
First let me say: thanks for a speedy response!

Second, let me ask:
> You grab the token from the auth header, call the Oauth provider's token validation endpoint and if it passes then act on their request

^ For this do you mean Ill need to write some stuff in my auth handler, that in addition to the isauthorized check on the okta global from Dance, I'd need to also check the request headers for Authorization Bearer, check that token against the Okta API?

**Comment by daenney** [comment]
You'll need 2 separate things:

* First you need a login flow that a user will have to go through. This is what you'll usually have on `/login`, it'll let them authenticate with Okta and you'll get an token in return. Usually that token is saved in a cookie in the browser session, but you can do with the token whatever you want, including show it to the user. You can do this flow in a CLI too, but you'll need to open a browser at some point and tell the user to copy the token. Be careful though b/c that token allows someone to act as that user.
* Now that the user/CLI has the token they can use it to do requests to your API endpoints, say `/api/v1/destroy_world`. In order to do so they'd do a request along the lines of `curl -X POST -H 'Authorization: Bearer <token>` https://apocalypse.now/api/v2/destroy_world`
* You have an API handler for that route. In that route you'll have to extract the token from the header. Once you have it you can turn back around and ask Okta "hey is this a valid token". If it is, then you can proceed with the request, if not something like a 401 should be returned to the client to let them know their token is invalid/expired

**Comment by jimcarreer** [comment]
> First you need a login flow that a user will have to go through. This is what you'll usually have on /login, it'll let them authenticate with Okta and you'll get an token in return. Usually that token is saved in a cookie in the browser session, but you can do with the token whatever you want, including show it to the user. You can do this flow in a CLI too, but you'll need to open a browser at some point and tell the user to copy the token. Be careful though b/c that token allows someone to act as that user.

^ Sorry bit confused as to why opening the browser becomes necessary? I mean say I'm handy with something like beautiful soup, I could pull it out that way right? I've played around with this and actually requests is pretty good at following the redirects like the browser would back to my app. And when I direct them to "open the browser" and show them the token, I'm guessing that would be done with a route in my application? 


Alright, could I use the okta.post(...) + their introspect API to check the token's validity?  Feels like I may have to hand roll my own client for checking bearer tokens

**Comment by daenney** [comment]
I wouldn't trust a CLI utility that just do that. It's really bad form to "optimise away" the authentication dialog with the Oauth provider. If I'm asked to log in with my Okta credentials, I expect to see the Okta login page. Anything short of that and I'm out.

**Comment by jimcarreer** [comment]
Yeah that's fair, I get that. So assuming I have a way to give the user their bearer token: I still need to do checks by:
1) Extracting it from the authentication header
2) Capturing this in the handler I have for checking authentication on a route (currently using a wrapper for that in flask, as you do)
3) If I see the header in my wrapper, I then need to go ask Okta "hey is this a good token" then either give them the 401 boot and let them pass?

Its kind of number 3 that I'm foggy about and seems like I can't use much in Dance at all for this part? Which I'm fine with, just trying to figure out all the bits.

**Comment by daenney** [comment]
Ya, number 3 is something you need to handle yourself. Flask-Dance is primarily meant to provide auth capabilities for UIs, not so much Oauth around an API.

It should be fairly simple to write a decorator for your routes thought that encapsulates the logic. One additional thing you might want to consider, though be careful about it, is caching the "is token OK state" for something like 5min so you don't incur the cost of talking to Okta on every request. Some tokens might also include an expiry by themselves, but that doesn't tell you if the token hasn't been revoked in the mean time.

**Comment by jimcarreer** [comment]
Cool, thanks for the tips, do you have and recommendations for libraries that could help out with #3 ?

**Comment by daenney** [comment]
Flask already lets you access the request, and thus the headers. Other than that you need to do an HTTP request to Okta, so requests or your preferred HTTP client.

I would suggest having a look at `functools` in stdlib, specifically `functools.wraps` for creating a decorator for the route to handle this for you. The other interesting one could be th `werkzeug.contrib.Cache` since that one has a built-in method for keys to expire after a period of time.

**Comment by jimcarreer** [comment]
For anyone re-reviewing this, I went with the above solution, which was also recommended by Okta
