### ISSUE TITLE
React, JWT, and Flask Dance

### ISSUE THREAD

**Issue by VortexH** [singingwolfboy/flask-dance#280]
Hi, right now, I have a working version of my app using Flask Dance and Semantic UI but we're transitioning to an architecture where the front end and back end are not tightly coupled.

Flask Dance handles the redirects to other pages but I'd like for React to handle this.

I've been reading articles on JWT and I'd like to use that for authentication on the front end but I'm not sure how to create a JWT token on my backend.

Going in this direction, I also don't want Flask Dance to handle the redirects, since I'm relying on React to handle that for me.

Is there any way to simply generate a JWT, pass that to the front end, and pass it to the back end when I need to access certain routes?

**Comment by daenney** [comment]
At this point I think you might need to reconsider you stack a bit. Flask-Dance is meant to help you do the oauth dance for a web UI. Since you're stripping it out entirely and moving to React this library as a whole doesn't really help you much anymore.

There's a number of libraries for React that handle oauth flows, and that's probably what you should use to now do the oauth dance. Once you have a token you can pass it on to backend services whichever way you like. Typically it's done by using the `Authorization` header, with a value of `Bearer: <token>`.
