### ISSUE TITLE
Fix for "MissingTokenError"

### ISSUE THREAD

**Issue by rebortg** [singingwolfboy/flask-dance#283]
there are some closed issues where user mention the "MissingTokenError". in my issue with Hubspot: [#211](https://github.com/singingwolfboy/flask-dance/issues/211)

in a Mention of this [solution](https://github.com/requests/requests-oauthlib/issues/324#issuecomment-501004440)

i added `include_client_id=True` [here](https://github.com/singingwolfboy/flask-dance/blob/a6d4d6455a518d313b638f65aff5630fe6909702/flask_dance/consumer/oauth2.py#L256) and it worked for hubspot
i don't want to create a PR because i don't know which things are influenced by it. Maybe we can this discuss it here first.

**Comment by singingwolfboy** [comment]
Flask-Dance does not provide a pre-set configuration for Hubspot, so this issue is not relevant. If someone wants to provide a pre-sent configuration for Hubspot, that would be great! Just follow the directions in the README: https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/contrib/README.rst

For now, I'm closing this issue.
