### ISSUE TITLE
Using a provider's token on a different website

### ISSUE THREAD

**Issue by FISHMANPET** [singingwolfboy/flask-dance#326]
I'm not sure how common this is use case is, or if what we're even doing is the best way to accomplish what we want, but here's the situation I find myself in:

I am trying to use an internal REST API that use a Google id_token for authorization, passing it in the headers as `X-API-KEY`.  I can easily extract the id_token out my google token, create the header dict, and pass that into requests.  However when the token expires, it will no longer be valid for my API.

Using the `google` object I can do something innocuous like `google.get("/oauth2/v1/userinfo")` to essentially validate that my token is valid and if not, automatically trigger the refresh, before I try to call my API.  I could also manually check the `expires_in` property and trigger a refresh (either by doing that userinfo call or somehow manually triggering the refresh process).

But I'm wondering if there's some way to have my cake and eat it too.  I realize that flask-dance is relying heavily on requests-oauthlib (which itself uses oauthlib), so it may be that my answer lies there somewhere, though I'm still trying to figure out how it's all connected right now.

**Comment by daenney** [comment]
You can use `google.get(https://some-other-domain.tld)`. If you use an absolute URL/domain like that, things will work. It doesn't let you pass headers, b/c the expectation here is that since we're doing oauth2 the auth header will be `Authorization: Bearer <token>`.

If you really need a custom header, you'll need to handle this yourself.
