### ISSUE TITLE
KeyError: 'google_oauth_state'

### ISSUE THREAD

**Issue by rmoorman** [singingwolfboy/flask-dance#34]
Hello,

I receive the error `KeyError: 'google_oauth_state'` in case the browser back button is hit after successful authentication (at least in the google authentication example provided)

### How to reproduce
Take this script which basically resembles the google authentication example
~~~~.python
from flask import Flask, redirect, url_for
from flask_dance.contrib.google import make_google_blueprint, google

app = Flask(__name__)
app.secret_key = "supersekrit"
app.debug = True
import os
os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"

blueprint = make_google_blueprint(
    client_id="my-key-here",
    client_secret="my-secret-here",
    scope=["profile", "email"]
)
app.register_blueprint(blueprint, url_prefix="/login")

@app.route("/")
def index():
    if not google.authorized:
        return redirect(url_for("google.login"))
    resp = google.get("https://www.googleapis.com/oauth2/v1/userinfo")
    assert resp.ok, resp.text
    return resp.text

if __name__ == "__main__":
    app.run()
~~~~
(Note that I set the OAUTHLIB_INSECURE_TRANSPORT environment variable as described in the docs but then in python code. Furthermore I used a different info url and just dump the whole response text. But I don't think that is relevant here)

The point is, if you start the app and navigate to it in the browser, You are sent to the google login screen. After that, you will be redirected to the appropriate blueprint url which then points you back to the index route. Fetching the userinfo is no problem either.
But when you hit the back button in your browser, the `KeyError` occurs which originates at flask_dance/consumer/oauth2.py on line 196.

**Comment by singingwolfboy** [comment]
Hmm, this is a tricky situation. The `google_oauth_state` key refers to the "state" variable that is [set in the `login()` view function](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/oauth2.py#L162-L167). This "state" variable is part of the OAuth spec, and it's a security measure to ensure that the OAuth provider correctly redirects the user to the same OAuth consumer that the client came from. (i.e. if you're trying to login with Google on my-website.com, then Google shouldn't redirect you back to evil-website.com instead.)

When you hit the back button on your browser, you'll go back to the Google provider, which will redirect you back to the Flask-Dance consumer. However, the effect is that you're doing the `authorized` step of the process without first doing the `login` step. The `authorized` step can't succeed without checking the "state" variable for security, and the "state" variable hasn't been set because the `login` step hasn't happened! And we can't just make this check optional -- doing that would completely invalidate the additional security that the "state" variable provides.

I suppose we could say that if the user hits the `authorized` step without having that "state" variable set, then we could redirect the user to the `login` step, effectively starting the OAuth dance all over again from the beginning. Does that seem like a reasonable solution?

**Comment by rmoorman** [comment]
Redirecting back to the login route in case the oauth state is missing sounds like a reasonable thing to do.
