### ISSUE TITLE
Allow forcing HTTPS regardless of reverse proxy?

### ISSUE THREAD

**Issue by colelloa** [singingwolfboy/flask-dance#374]
Hey,

Thanks for making and maintaining this library - it is great! I'm here to make a case for allowing forcing HTTPS in the redirect URI instead of relying on flask's request introspection + proper proxy setups.

I know this has come up before - redirect mismatch, use werkzeug proxy fix, etc.

Still, with the diversity of webapp deployments (e.g. behind an external load balancer that forwards 443 -> 80 of an instance that hosts nginx, which then forwards from 80 -> a local socket for performance), it gets pretty difficult to get reverse proxies working properly for flask in all cases.

More important, these is an incredibly easy workaround to this with url_for - _scheme='https'
https://stackoverflow.com/questions/14810795/flask-url-for-generating-http-url-instead-of-https/26636880

I have a fork of this repo that does some super minor changes to allow forcing https in the redirect URI. 

https://github.com/colelloa/flask-dance/commit/7f68aa5f4b56ef523e8f6a86ab9675bd35c576b6

I've only implemented this for google, because it recently killed http and forces https, but I am happy to expand this fork to include all if this change is possible?

Is there any reason why this library relies on flask itself for the URL? Is it worth opening up a PR and adding to some test cases?

Thanks very much for the time.
-Andrew

**Comment by singingwolfboy** [comment]
This gets a bit into the philosophy of "practicality vs purity". My perspective is, one of the traits of a good framework is that it guides developers towards the best solution. That means encouraging a proper understanding of _what_ you're doing and _why_ you're doing it, especially when the consequences of getting it wrong are severe. HTTP vs HTTPS is a security issue (that's what the S in HTTPS stands for), and getting security issues wrong can have severe consequences.

In this case, the best solution to this problem is to make sure that _all_ URLs are automatically HTTPS. That way, the entire question of "HTTP vs HTTPS" is eliminated -- your project does the right thing everywhere. There's no risk of breaking OAuth due to insecure URLs. There's no risk of [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) problems in the browser. There's no risk of your users being affected by man-in-the-middle (MITM) attacks, which HTTPS is designed to prevent. It's just better all the way around.

The alternative is a patchy, incomplete system where the developer must remember to manually rewrite all URLs to HTTPS -- and that's never a reliable solution. Somewhere, something will go wrong -- even if that something is completely unrelated to Flask-Dance! -- and there will be security issues. I would much rather force developers to debug their HTTPS issues _before_ their website goes live, than risk something going wrong with their patchy, manual implementation _after_ it's already live and serving users.

Security can be annoying, but it's there for a reason. If someone has trouble unlocking their front door, the solution is to fix the lock, not remove it. If someone is having trouble remembering their passwords, the solution is to use a password manager, not using the same easy-to-guess password everywhere. And in this case, if a developer is having trouble with generating HTTPS URLs, the solution is to make those URLs generate with HTTPS everywhere by default, not to override them on a case-by-case basis.

Does that make sense?
