### ISSUE TITLE
working outside of application context

### ISSUE THREAD

**Issue by citizenken** [singingwolfboy/flask-dance#41]
I'm fairly new to Flask, and am using Github authentication. I'm running into an issue when I try to access the Github object outside of the controller. I want to use the api to create an object in-memory dictionary so I can easily access repo and branch info. You can see a bit of example code here https://gist.github.com/citizenken/f29f639de44d20e97bb4.

When I do a `github.authenticated` check in a Flask route in controller.py, github instantiates properly. When I try to access `github.authenticated` in lib.py as the app starts up, github instantiates as `<LocalProxy unbound>` and I get the following stack trace:
    
    Traceback (most recent call last):
      File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 2358, in <module>
        globals = debugger.run(setup['file'], None, None, is_module)
      File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1778, in run
        pydev_imports.execfile(file, globals, locals)  # execute the script
      File "/repo/launch_my_package.py", line 2, in <module>
        from my_package import app
      File "/repo/my_package/__init__.py", line 11, in <module>
        import controller
      File "/repo/my_package/controller.py", line 7, in <module>
        from lib import gitservice
      File "/repo/my_package/lib.py", line 36, in <module>
        gitservice = GitService()
      File "/repo/my_package/lib.py", line 22, in __init__
        self.get_refs()
      File "/repo/my_package/lib.py", line 26, in get_refs
        if github.authorized:
      File "/repo/my_package_venv/lib/python2.7/site-packages/werkzeug/local.py", line 342, in __getattr__
        return getattr(self._get_current_object(), name)
      File "/repo/my_package_venv/lib/python2.7/site-packages/werkzeug/local.py", line 301, in _get_current_object
        return self.__local()
      File "/repo/my_package_venv/lib/python2.7/site-packages/flask/globals.py", line 27, in _lookup_app_object
        raise RuntimeError('working outside of application context')
    RuntimeError: working outside of application context

What exactly is happening here? I have a token stored in the DB, and I am able to interact with the API inside the controller, so I don't think authorization is the problem.

Any help would be great!

**Comment by singingwolfboy** [comment]
Hi @citizenken, the reason you're seeing this is because the `flask.ext.dance.contrib.github.github` object is a [`LocalProxy`](http://werkzeug.pocoo.org/docs/0.11/local/#werkzeug.local.LocalProxy) object, which points to a [requests session](http://docs.python-requests.org/en/latest/api/#request-sessions) that is scoped to the current application context. Flask is designed to allow you to create and manage multiple applications at a time, but only have one active for any given HTTP request. See also the [docs for the Flask application context](http://flask.pocoo.org/docs/0.10/appcontext/).

If you want to access the requests session outside of an application context, you can do so by referring to [the `session` attribute of the blueprint object](https://flask-dance.readthedocs.org/en/latest/api.html#flask_dance.consumer.OAuth2ConsumerBlueprint.session). Clearly, this is confusing -- otherwise, you wouldn't have asked about it! Can you suggest some way to improve the documentation so that it's easier for developers to discover why this doesn't work, and what to do instead? A pull request would be amazing, but even some comments or suggestions would be helpful.

**Comment by citizenken** [comment]
Thanks for the quick reply! I think a section in the docs about use outside of controller routes/application context might be helpful. After the holidays I'll put up a doc PR for you.

**Comment by singingwolfboy** [comment]
That would be great! Thank you so much! :smile: 

I should also mention that the blueprint object should be passed around, rather than the session object. The session should be referred to as necessary, but allowed to fall out of scope so that new sessions can be dynamically constructed as necessary. For example, this is the *wrong* thing to do:
```python
# ANTI-PATTERN: DO NOT DO THIS
github = github_blueprint.session

def called_outside_of_application_context():
    resp = github.get(...)
    # WRONG, BAD THINGS WILL HAPPEN
```
It's wrong because [the `session` attribute is constructed lazily](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/oauth2.py#L149-L150), using the [`lazy`](http://pythonhosted.org/lazy/) module, and [intended to be torn down after each request](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/oauth2.py#L168-L169). Trying to re-use the same session could lead to cache invalidation problems, particularly around authorizing new users, refreshing tokens, and using multiple different OAuth providers. The only reason why you can use the `flask.ext.dance.contrib.github.github` reference this way is because it's not actually a reference to the session itself, it's a LocalProxy to a new session that gets created before the Flask request is handled, and gets torn down after the request is completed.

This is the *right* thing to do:
```python
def called_outside_of_application_context():
    resp = github_blueprint.session.get(...)
```
This way, there's no variable reference to the `session` attribute, so it can get garbage collected and a new one will be created as necessary.

**Comment by citizenken** [comment]
I was actually about to use the anti-pattern, so thanks a lot for the explanation/example

**Comment by singingwolfboy** [comment]
@citizenken are you still planning to write that documentation? You closed the issue, and I don't know if that means that you aren't planning to do it, after all.

**Comment by citizenken** [comment]
Oh no, I can write that, I just didn't want to clutter up the issues with
one that has been resolved. I can open it back up again.

**Comment by singingwolfboy** [comment]
However you want to organize your work is up to you. If having the open issue doesn't help, then we should leave it closed.
