### ISSUE TITLE
sqla-multiuser.rst broken by Flask-Login 0.3.0 changes

### ISSUE THREAD

**Issue by vassudanagunta** [singingwolfboy/flask-dance#48]
The home.html template produces the following error:

builtins.AttributeError
AttributeError: 'bool' object has no attribute '__call__'

Cause: "Since 0.3.0, Flask-Login has set `is_active` `is_authenticated` `is_anonymous` to property in `UserMixin`, so we should use `current_user.is_authenticated` instead of `current_user.is_authenticated()`." See miguelgrinberg/flasky#74.

**Comment by singingwolfboy** [comment]
@vassudanagunta: Thanks for catching that! Would you like to make a pull request to fix it? It's not hard, and you can then proudly tell your friends that you contributed to an open source project that you use. :)

Just fork the repository, edit the `flask-dance/docs/quickstarts/sqla-multiuser.rst` file in your fork, and send a pull request! Then I'll review it, and if it looks good, I'll merge it. :+1:

**Comment by vassudanagunta** [comment]
Done. Does it make sense to open an Issue in the future when you already have a fix ready to pull request? Seems like a lot of noise doing it the way I did it!

**Comment by singingwolfboy** [comment]
@vassudanagunta: Welcome to the wonderful world of open source, and congrats on your first pull request!

In general, if you already have a fix for a problem you see in an open source project, you should just make the pull request. It's entirely possible that the "problem" that you see is intentional, or that the fix you're suggesting isn't the right fix to make, but even if that's the case, you and the maintainer can discuss that on the pull request, and the maintainer can see *exactly* what you think needs to be changed, which is helpful.

If you want to report a problem, request a feature, or in general do something where you *don't* have a code change that accomplishes what you're looking for, that's generally when you want to file an issue. Maintainers generally prefer pull requests to issues, but if you don't have the time, knowledge, or motivation to write a fix/improvement, then reporting an issue is better than nothing.

**Comment by vassudanagunta** [comment]
got it. thanks!
