### ISSUE TITLE
Security considerations

### ISSUE THREAD

**Issue by matt3o** [singingwolfboy/flask-dance#61]
Hey, I am currently digging in the Python OAuth area and wanted to share some insights / security considerations.
1) Flask Session is not the right place to store access_tokens as it is only Base64 encoded. ["As per the RFC, "[tokens] MUST be kept confidential in transit and storage."  ](https://github.com/lepture/example-oauth2-server/issues/21)
A secure alternative is the use of server side sessions with [Flask Session (the addon)](https://pythonhosted.org/Flask-Session/) or as it is promoted in the docs - storing it in a database on the server side. 
--> In my opinion this should be clarified on the front page - the default option == cookies is not secure
See also http://security.stackexchange.com/questions/115695/when-should-server-side-sessions-be-used-instead-of-client-side-sessions/115714#115714
2) From glancing over the code I wasn't sure but I assume Flask Dance uses the state parameter internally? Or is it up to the developer using Flask Dance to make sure the state parameter is used?

**Comment by singingwolfboy** [comment]
Sorry it took me so long to respond. I appreciate you auditing the Flask-Dance codebase for security concerns -- security is an important factor to consider for any project! However, I don't think that keeping access token in cookies is insecure.

HTTP cookies are stored in the user's browser, which means that the user can read and modify that data if she wishes. (Flask's [secret_key](http://flask.pocoo.org/docs/0.11/api/#flask.Flask.secret_key) means that users can't even do *that* unless they know the secret key on the server, but for the sake of argument, let's say a smart user has figured out the key and has access to the data in her own cookie.) However, each user only has access to their own cookie data, not that of other users. As a result, the security implications of keeping OAuth access tokens in a cookie is that a user can read and modify her own OAuth access token.

Well, a user reading her own access token is no big deal: the user already knows her own username and password to the OAuth provider service, so there's no reason why the user *needs* an access token in order to do anything on that provider service. Modifying the access token is similarly no big deal: if the user has obtained someone else's OAuth access token, then she could theoretically swap out her own access token with the stolen access token in the cookie -- but once the user has obtained someone else's OAuth access token, that user is *already* able to make requests to the provider's API using that stolen access token, and there's nothing worse they can do by swapping the access token in the cookie.

Please let me know if you can come up with some kind of exploit that involves a user being able to read and modify her own OAuth access token. If so, I'm happy to indicate that the default storage option is insecure, and push developers to store OAuth access tokens in a database instead. But without an exploit, I think the primary reason to encourage developers to use the database backend is for user convenience, so a user doesn't have to go through the OAuth flow every time they use a different browser.

**Comment by singingwolfboy** [comment]
And yes, Flask-Dance does use the `state` parameter internally. It's done in two parts: [setting login state](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/oauth2.py#L177-L182), and [verifying that state on the authorized callback](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/oauth2.py#L212-L221).

**Comment by matt3o** [comment]
No problem ;) 
About the cookie part: The content of the cookie is not secure, that's my point. (Watch / Read this: http://blog.miguelgrinberg.com/post/how-secure-is-the-flask-user-session --> He decodes the cookie because it is just Base64 encoded and signed). The browser user can see the access token if he wants to (Though he cannot modify it without the server - it is signed with the secret key). This is of course not inherently insecure but it should be discouraged for production use. For all I know Browser Cookie should not be considered a safe place as another website can potentially gain access e.g. by a Browser bug or a CSRF. 
There are two solutions to this problem: 1) Really encrypt the Cookie or 2) use a server-side storage like e.g. Flask Session offers. 
This is also why I included state  - I saw a few hours later that it is used and verified in the project which is very good. I fear a lot of big projects don't do this and combined with the cookie security you can actually fish the access token via CSRF - kind of creepy when there is also a refresh token stored. 
Hope this helps!

**Comment by singingwolfboy** [comment]
OK, so cookies are readable. As I said, I still don't see how that's a security vulnerability for a user's own OAuth access tokens.

**Comment by matt3o** [comment]
That's completely up to you. I wrote you all that I know - and it is no real bad thing as you are using the state parameter of Oauth2. Nevertheless in my opinion unencrypted Cookies should not be used in production as this a violation of the confidentiality of the tokens.

**Comment by singingwolfboy** [comment]
Alright, in that case I'm going to close this issue, as I don't think there's anything that needs to be done here.
