### ISSUE TITLE
OAuth table's user_id column is null?

### ISSUE THREAD

**Issue by NathanWailes** [singingwolfboy/flask-dance#87]
I've been following [this video](https://www.youtube.com/watch?v=G44Tpi58dcc), which appears to be a slight extension of the information available in the docs. I've done some things a little differently from the way he does things in the video, and everything appears to be working, but the `OAuth` table's `user_id` column is `null` for the record that gets created.

**Comment by singingwolfboy** [comment]
Hey @NathanWailes, thanks for pointing me to that video -- I had no idea that people were making video tutorials about this project! I'm very excited about that. 💖 

[The documentation for the SQLAlchemy backend](https://flask-dance.readthedocs.io/en/latest/backends.html#sqlalchemy) points out that there are two different ways you can use it:

* Your entire website uses one account on the remote service. For example, one GitHub account for your entire website, one Twitter account for your entire website, etc. This is handy if your website doesn't have user accounts, but is basically operating as a bot using that service.
* Your website has per-user accounts on the remote service. For example, your website has a user account system, and each user connects to their individual GitHub account, Twitter account, and so on. This is handy if you want to do a traditional "login with Twitter" button to allow users to sign up for your website without creating a new password.

In the first case, the `user_id` column will always be `null` for the created record, since there is no user to associate the remote account with. Is this the situation you're running into?

Also, if the documentation is unclear, I'd really love some assistance with making it clearer!

**Comment by NathanWailes** [comment]
I'm in the second situation: my website has user accounts, and I want users to be able to sign up/in either with their email address, Twitter account, or Facebook account, and if they sign up with one method and then sign in with another, I want the system to be able to *not* create two accounts but instead associate the new sign-in method with the existing account.

What's confusing to me is that I am creating the user record manually, and my guess is that the OAuth db record exists before the user record, and so how is that `user_id` field supposed to get populated?

Also, I'll definitely try to help with making the documentation clearer. It'll just depend on how much I can understand.

**Comment by singingwolfboy** [comment]
I tried doing this in one of my personal project. The codebase is in a private repository on GitLab, but I've extracted the relevant code, [and put it in a GitHub gist](https://gist.github.com/singingwolfboy/eaea1fdc6c9a683a75feea4a27f7dc31). The basic idea is, if you're doing something fancy with how the OAuth database record is being created, you can just return `False` from the `oauth_authorized` signal handler, to indicate to Flask-Dance that it shouldn't even try to make the database record for you. That way, you can do it all yourself, in exactly the way that you want.

I realize that this code is very complicated, but I'm not sure of a way to simplify it without being too restricting. I'm happy to discuss ways to make it better, and pull requests are very welcome!

**Comment by NathanWailes** [comment]
I spent a while reading over the code and trying to put it into my project, and I have a question about this section of code:

    # Find this OAuth token in the database, or create it
    query = OAuth.query.filter_by(
        provider=blueprint.name,
        provider_user_id=github_user_id,
    )
    try:
        oauth = query.one()
    except NoResultFound:
        github_user_login = str(github_info["login"])
        oauth = OAuth(
            provider=blueprint.name,
            provider_user_id=github_user_id,
            provider_user_login=github_user_login,
            token=token,
        )

From reading over the rest of that function, it seems like if a user logs in once with Twitter, and we save that token to the OAuth table, and then that token expires or the user deauthorizes the app, then user tries to log in again with that same provider (eg Twitter), then we will see that there is already a token in the db and not update it, even though it has expired.

Is that an accurate reading of that code?

**Comment by singingwolfboy** [comment]
That's correct. However, if you want to update the token, I'm not sure this is the right place to do it, anyway. How do you find out whether the token has expired? I believe it happens after you try to use it, and discover a 401 status code instead of the result you were expecting. When that happens, you can delete the token from the database, log the user out, and flash a message indicating that they need to reauthorize with Twitter. Next, they'll try to go through the login flow again, and since the token has been deleted from the database, the query will raise `NoResultsFound`, which is exactly what we want.

**Comment by NathanWailes** [comment]
Ok, I think I understand the idea; thanks!
