### ISSUE TITLE
How does twitter.authorized know it's me?

### ISSUE THREAD

**Issue by NathanWailes** [singingwolfboy/flask-dance#88]
I don't really understand how I can log out, delete my cookie, then click the "Sign in with Twitter" button and it somehow knows who I am and just logs me in directly. `twitter.authorized` is evaluating to `True`, and I saw that the code I think that's being evaluating to True is:

    bool(self._client.client.client_secret) and
    bool(self._client.client.resource_owner_key) and
    bool(self._client.client.resource_owner_secret)

How can the session still have a `resource_owner_key` and `resource_owner_secret` after I've logged out, deleted my session cookie in Chrome, and restarted the server?

**Comment by singingwolfboy** [comment]
Because although you've logged out of your local website, you _haven't_ logged out of Twitter.com. When you try to log in with Twitter using OAuth, the following things happen:

1. Flask-Dance sends you to Twitter, along with some information about who sent you there.
2. Twitter checks who sent you, and asks that you log in to Twitter. After you're logged in, Twitter asks you if you're OK with sharing your information with the website that sent you.
3. When you agree, Twitter sends you back to the original website, along with a special token that the original website can use to call the Twitter API on your behalf.

Even if you log out of your website, restart everything, and so on, that doesn't change anything from Twitter's point of view. When you get to step 2 of the OAuth dance, Twitter is smart enough to see that you are _already_ logged in on Twitter, and you have _already_ agreed to sharing your information with this particular website, so they don't bother to make you confirm a second time. Instead, they just send you right back to the original website, with the special token for that website to use.

Does that make sense? If you want to truly start over the OAuth dance (usually for purposes of testing), you have to go to the provider website and revoke your permission for sharing information with the consumer website. In the case of Twitter, specifically, go to [the Apps section of your Twitter settings](https://twitter.com/settings/applications) and revoke the permission for your Twitter app. After you do that, if you try to use Flask-Dance to login with Twitter, Twitter will once again ask you for permission to share your information with the other website.

**Comment by NathanWailes** [comment]
Thank you for that in-depth explanation!

So is it accurate to say that calling `twitter.authorized` pings Twitter?

**Comment by singingwolfboy** [comment]
No, it doesn't. If you have code that looks like this:

```python
@app.route('/')
def index():
    if not twitter.authorized:
        return redirect(url_for('twitter.login'))
    # view continues here
```

The first time you hit this code, `twitter.authorized` will be False. That will start a chain of redirects that:

* sends you to Twitter
* sends you back to the `/twitter/authorized` page
* sends you back to the index page

That will cause this code to run a _second_ time, and at _that_ point, `twitter.authorized` will be True. That's why it appears to all work so seamlessly. Does that make sense?

**Comment by NathanWailes** [comment]
Ok, I'm still confused, because I was logging out, deleting my cookie for my website, then hitting the 'log in with twitter' button with a breakpoint set on that `if not twitter.authorized` line, and I was running `twitter.authorized` in my debugger console, and it was evaluating to True immediately. And so if it hadn't yet pinged Twitter or redirected me, how did it know who I (the user) was?

**Comment by singingwolfboy** [comment]
Hmm, that _is_ mysterious! I forgot that Twitter is using OAuth 1 instead of OAuth 2, which makes the logic different -- I may have unintentionally lied to you earlier. I don't have time to look into this more right now, but I'll see if I can figure it out later!

**Comment by NathanWailes** [comment]
More experiments done:
- If I log out of my Twitter account and then log into a *different* Twitter account, then access my index page and set a breakpoint before it returns the template, `twitter.token` returns the token from the first (logged-out) Twitter account.
- If I open an incognito window in Chrome and access the index page, the `twitter.token` value is still the value from my non-incognito browser session.

**Comment by NathanWailes** [comment]
Ok, I think I've figured it out. I think the problem is with `sqla.py`, specifically these lines:

    def get(self, blueprint, user=None, user_id=None):
        # check cache
        cache_key = self.make_cache_key(blueprint=blueprint, user=user, user_id=user_id)
        token = self.cache.get(cache_key)
        if token:
            return token

I think what is happening is that because my code isn't fully hooked up, the `user_id` column in my `OAuth` db table is `None`, and so both the `cache_key` and also the db call are using "None" as a valid unique identifier. Which means that when I log out, because my `user_id` is still `None`, the `twitter_blueprint` is still faced with the same information for looking up users, and thus it retrieves the same record.

**Comment by singingwolfboy** [comment]
Ah hah! Cache invalidation is one of the famously hard problems of computer science, and it looks like that's the root of the problem here. Are you using Flask-Cache here, or does this bug show up with the [`FakeCache`](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/utils.py#L22) implementation?

Is there any chance you can write an automated test that identifies this bug? That will make it easier to fix it so that it _stays_ fixed.

**Comment by NathanWailes** [comment]
I don't think the problem is that the cache isn't being invalidated when it should be; I think it's that the cache is allowing an entry to be created when the `user_id` field of the `OAuth` table entry is `None`, and so it then isn't able to distinguish between a logged-in user and a logged-out user.

Honestly, what I would be inclined to do is to just raise an exception if either(? or both?) the `user_id` and the `user` parameters are `None`:

    def get(self, blueprint, user=None, user_id=None):
        if not user and not user_id:
            raise ValueError("Either 'user' or 'user_id' must be specified.")
        (...)

    def set(self, blueprint, token, user=None, user_id=None):
        if not user and not user_id:
            raise ValueError("Either 'user' or 'user_id' must be specified.")
        (...)

**Comment by singingwolfboy** [comment]
That doesn't allow for using Flask-Dance without a user account system. (See [the first option in this comment](https://github.com/singingwolfboy/flask-dance/issues/87#issuecomment-340247706).) Maybe this is a problem that needs to be solved with better documentation?

**Comment by NathanWailes** [comment]
Could you maybe force the developer to explicitly declare whether they want the OAuth to be linked with a user account system or not? And then have the exceptions depend on that?

**Comment by singingwolfboy** [comment]
Can you suggest an API for doing so? Which is to say, imagine that this feature was already implemented, and write some code that uses this already-implemented feature. That will help me understand what you're suggesting.

**Comment by NathanWailes** [comment]
Yeah, so right now my `twitter_blueprint` declaration(?) in my app.py looks like this:

```
twitter_blueprint = make_twitter_blueprint(
    api_key=config['twitter']['api_key'],
    api_secret=config['twitter']['api_secret'],
    redirect_to="web_routes.lyrics_rhythm_recorder"
)
```

I'm suggesting just adding a required parameter, so it'd look like this:

```
twitter_blueprint = make_twitter_blueprint(
    link_tokens_to_user_accounts=True,
    api_key=config['twitter']['api_key'],
    api_secret=config['twitter']['api_secret'],
    redirect_to="web_routes.lyrics_rhythm_recorder"
)
```

**Comment by NathanWailes** [comment]
Update: 

Ok, two things:

1) I just realized that because I want the exception-raisers to be in the `sqla.py` file, it might make more sense to have the parameter as part of the `twitter_blueprint.SQLAlchemyBackend()` initialization.

2) I also realized that I already have information in the `twitter_blueprint.SQLAlchemyBackend()` which seems like it might be sufficient to handle this situation without needing an additional parameter: the `user=current_user` parameter.

Here's what my code looks like right now:

`twitter_blueprint.backend = SQLAlchemyBackend(OAuth, db.session, user=current_user)`

So it *might* be sufficient to simply look for whether that `user` parameter is set to `current_user` or not. I'm not positive, but I figured it was worth bringing up.
