### ISSUE TITLE
Should expired tokens be getting deleted from the db automatically?

### ISSUE THREAD

**Issue by NathanWailes** [singingwolfboy/flask-dance#89]
I deauthorized my app from my Twitter account's settings page, and the code is getting a 401 response when it pings the Twitter servers, but it isn't automatically deleting the oauth record and redirecting the user to Twitter to re-authorize the app.

I noticed [this issue](https://github.com/singingwolfboy/flask-dance/issues/35) which seems somewhat similar.

**Comment by singingwolfboy** [comment]
An OAuth provider isn't required to notify a consumer website when the user has revoked their permission, and as far as I know, none of them do. What that means is, when you deauthorize your app from the Twitter account settings page, Twitter doesn't inform your app that a user has deauthorized it. As a result, there's no way for your app to know that the OAuth record should be deleted from the database at that point in time.

It's possible to automatically delete the OAuth record when you receive a 401 response from Twitter if you try and fail to make an API request, but that's not something that I want to implement automatically. What if the Twitter API screws up and accidentally responds with a 401 when it should have succeeded? If so, most of the time you'd want to try again later, rather than instantly deleting data from your database.

If you really want your application to automatically delete the OAuth record on the first 401 response, you can implement that yourself. Every time you make an API request, check the response code, and if it's 401, then delete the OAuth record.

**Comment by NathanWailes** [comment]
Ok got it, thanks!
