### ISSUE TITLE
Wrap known oauthlib errors with an intelligible message

### ISSUE THREAD

**Issue by maxrothman** [singingwolfboy/flask-dance#9]
Two common uses of flask-dance require environment variables to be set for oauthlib to work.
- `OAUTHLIB_RELAX_TOKEN_SCOPE=1`: allow changing scopes (needed for google?)
- `OAUTHLIB_INSECURE_TRANSPORT=1`: allow redirecting back to a non-https site

By catching these errors and raising something with a more informative message, users could avoid having to dive into flask-dance code to figure out what's necessary to fix these.

**Comment by singingwolfboy** [comment]
I don't think that catching these errors is a good idea, since that makes it more difficult to trace where they came from and what they mean. I've tried to document these environment variables better in the quickstarts, so I'm closing this issue for now. If you think it's still a problem, you can reopen it or open a new issue.
