### ISSUE TITLE
Typo in docs?

### ISSUE THREAD

**Issue by seekheart** [singingwolfboy/flask-dance#96]
https://flask-dance.readthedocs.io/en/latest/backends.html#custom

In the custom you are calling super on FileStorage and not FileBackend is this a typo? Also for the args what does the blueprint parameter do, it seems to be unused?

**Comment by singingwolfboy** [comment]
Yes, that _is_ a typo! Would you mind making a pull request to fix it? https://github.com/singingwolfboy/flask-dance/blob/master/docs/backends.rst

The `blueprint` parameter isn't used in that particular backend, but it's provided so that it _could_ be used if it makes sense to do so. For example, [the SQLAlchemy backend uses it to determine the provider name when making database queries](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/backend/sqla.py#L130).

**Comment by seekheart** [comment]
Yup I’ll make the PR shortly after I get on a pc :)

**Comment by seekheart** [comment]
@singingwolfboy all set :)
