### ISSUE TITLE
Question regrading Custom Backends

### ISSUE THREAD

**Issue by seekheart** [singingwolfboy/flask-dance#98]
I'm writing a custom backend that uses pymongo to find the current user.
Question is from the documentation I'm not sure how the custom backend would know what the username I'm passing in is? Is that where the blueprint argument comes in to play or?

for reference this snippet from docs:

```python
import os
import os.path
import json
from flask_dance.consumer.backend import BaseBackend

class FileBackend(BaseBackend):
    def __init__(self, filepath):
        super(FileBackend, self).__init__()
        self.filepath = filepath

    def get(self, blueprint):
        if not os.path.exists(self.filepath):
            return None
        with open(self.filepath) as f:
            return json.load(f)

    def set(self, blueprint, token):
        with open(self.filepath, "w") as f:
            json.dump(token, f)

    def delete(self, blueprint):
        os.remove(self.filepath)
```

Where does the user info live?

**Comment by singingwolfboy** [comment]
User information can be stored in different ways. In your case, you're probably storing user information in MongoDB, but Flask-Dance doesn't know _anything_ about MongoDB right now. So how could it get information about the user and automatically provide it to the backend? It can't.

However, you can write your backend so that it receives extra information when you initialize the backend. [That's how how the SQLAlchemy backend works](http://flask-dance.readthedocs.io/en/latest/backends.html#sqlalchemy) -- you have to pass in a connection to a SQLAlchemy database, and you have to pass in information for how the backend can look up the current user.

I assume that the way that you look up user information in MongoDB is fairly different from the way that you look up user information in SQLAlchemy. You'll have to write your backend so that the developer can pass it a way to look up user information, and configure your backend to use the lookup mechanism that the developer provides. Does that make sense?

**Comment by seekheart** [comment]
My question is how do I get the info about the user and pass to my backend?

**Comment by singingwolfboy** [comment]
That's up to you. You'll have to design an API for that.

**Comment by singingwolfboy** [comment]
@seekheart Do you understand how to do this? I'm happy to help if I can, but I don't know how user information is generally stored in pymongo.

**Comment by singingwolfboy** [comment]
Since I haven't heard back from you, I'll assume that you're not interested in pursuing this.

You may want to talk to @blohinn about this, since he indicated in #102 that he is using a custom pymongo backend.
